# Generated by Django 5.1.4 on 2026-03-17 17:54

import depenses.models
import depenses.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDepenseExploitation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_saisie', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de saisie')),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('devise', models.CharField(choices=[('XOF', 'XOF (Franc CFA)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dollar US)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[depenses.validators.validate_montant_positif], verbose_name='Montant')),
                ('montant_xof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculé automatiquement selon le taux au moment de la saisie.', max_digits=15, verbose_name='Montant converti XOF')),
                ('taux_change_utilise', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), editable=False, max_digits=10, verbose_name='Taux de change utilisé')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('numero_piece', models.CharField(blank=True, max_length=100, verbose_name='Numéro de pièce')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('numero_saisie', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numéro de saisie')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('ligne_budgetaire', models.CharField(choices=[('etude', 'Étude'), ('materiel', 'Matériel et équipement'), ('logistique', 'Logistique'), ('soustraitance', 'Sous-traitance'), ('frais_mission', 'Frais de mission')], db_index=True, max_length=20, verbose_name='Ligne budgétaire')),
                ('nature_depense', models.CharField(choices=[('proformat', 'Proformat'), ('bon_commande', 'Bon de commande'), ('demande_achat', "Demande d'achat"), ('facture', 'Facture')], max_length=20, verbose_name='Nature de la dépense')),
                ('piece_jointe', models.TextField(blank=True, max_length=100, null=True, validators=[depenses.validators.validate_file_extension, depenses.validators.validate_file_size], verbose_name='Pièce jointe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('centre_budgetaire', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projets.projet', verbose_name='Centre budgétaire (Projet)')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': "historical Dépenses d'exploitation",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepenseFraisGeneraux',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_saisie', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de saisie')),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('devise', models.CharField(choices=[('XOF', 'XOF (Franc CFA)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dollar US)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[depenses.validators.validate_montant_positif], verbose_name='Montant')),
                ('montant_xof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculé automatiquement selon le taux au moment de la saisie.', max_digits=15, verbose_name='Montant converti XOF')),
                ('taux_change_utilise', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), editable=False, max_digits=10, verbose_name='Taux de change utilisé')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('numero_piece', models.CharField(blank=True, max_length=100, verbose_name='Numéro de pièce')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('numero_saisie', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numéro de saisie')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='Modifié le')),
                ('ligne_budgetaire', models.CharField(choices=[('loyers', 'Loyers'), ('cie', 'CIE'), ('sodeci', 'SODECI'), ('dotation_carburant', 'Dotation carburant'), ('frais_taxi', 'Frais taxi'), ('fournitures_bureau', 'Fournitures bureau'), ('produits_entretien', 'Produits entretien & droguerie'), ('assurance_sante', 'Assurance santé'), ('charges_personnel', 'Charges personnel'), ('telephone_fixe', 'Téléphone fixe & internet'), ('telephone_cellulaire', 'Téléphone cellulaire'), ('entretien_vehicule', 'Entretien véhicule'), ('impots', 'Impôts'), ('bic', 'BIC'), ('patente', 'Patente'), ('cnps', 'CNPS'), ('entretien_informatique', 'Entretien informatique & télécom')], db_index=True, max_length=30, verbose_name='Ligne budgétaire')),
                ('nature_depense', models.CharField(choices=[('demande_achat', "Demande d'achat"), ('bon_commande', 'Bon de commande'), ('demande_paiement', 'Demande de paiement'), ('demande_travail', 'Demande de travail'), ('demande_absence', "Demande d'absence"), ('facture', 'Facture'), ('frais_mission', 'Frais de mission'), ('reservation', 'Réservation')], max_length=20, verbose_name='Nature de la dépense')),
                ('piece_jointe', models.TextField(blank=True, max_length=100, null=True, validators=[depenses.validators.validate_file_extension, depenses.validators.validate_file_size], verbose_name='Pièce jointe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Dépenses de frais généraux',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DepenseExploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de saisie')),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('devise', models.CharField(choices=[('XOF', 'XOF (Franc CFA)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dollar US)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[depenses.validators.validate_montant_positif], verbose_name='Montant')),
                ('montant_xof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculé automatiquement selon le taux au moment de la saisie.', max_digits=15, verbose_name='Montant converti XOF')),
                ('taux_change_utilise', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), editable=False, max_digits=10, verbose_name='Taux de change utilisé')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('numero_piece', models.CharField(blank=True, max_length=100, verbose_name='Numéro de pièce')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('numero_saisie', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Numéro de saisie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ligne_budgetaire', models.CharField(choices=[('etude', 'Étude'), ('materiel', 'Matériel et équipement'), ('logistique', 'Logistique'), ('soustraitance', 'Sous-traitance'), ('frais_mission', 'Frais de mission')], db_index=True, max_length=20, verbose_name='Ligne budgétaire')),
                ('nature_depense', models.CharField(choices=[('proformat', 'Proformat'), ('bon_commande', 'Bon de commande'), ('demande_achat', "Demande d'achat"), ('facture', 'Facture')], max_length=20, verbose_name='Nature de la dépense')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to=depenses.models.exploitation_upload_path, validators=[depenses.validators.validate_file_extension, depenses.validators.validate_file_size], verbose_name='Pièce jointe')),
                ('centre_budgetaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_exploitation', to='projets.projet', verbose_name='Centre budgétaire (Projet)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': "Dépense d'exploitation",
                'verbose_name_plural': "Dépenses d'exploitation",
                'ordering': ['-date_saisie', '-date_creation'],
                'indexes': [models.Index(fields=['centre_budgetaire', 'ligne_budgetaire'], name='depenses_de_centre__67ad25_idx'), models.Index(fields=['date_saisie'], name='depenses_de_date_sa_29a7c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepenseFraisGeneraux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de saisie')),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('devise', models.CharField(choices=[('XOF', 'XOF (Franc CFA)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dollar US)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[depenses.validators.validate_montant_positif], verbose_name='Montant')),
                ('montant_xof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculé automatiquement selon le taux au moment de la saisie.', max_digits=15, verbose_name='Montant converti XOF')),
                ('taux_change_utilise', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), editable=False, max_digits=10, verbose_name='Taux de change utilisé')),
                ('fournisseur', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('numero_piece', models.CharField(blank=True, max_length=100, verbose_name='Numéro de pièce')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('numero_saisie', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Numéro de saisie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ligne_budgetaire', models.CharField(choices=[('loyers', 'Loyers'), ('cie', 'CIE'), ('sodeci', 'SODECI'), ('dotation_carburant', 'Dotation carburant'), ('frais_taxi', 'Frais taxi'), ('fournitures_bureau', 'Fournitures bureau'), ('produits_entretien', 'Produits entretien & droguerie'), ('assurance_sante', 'Assurance santé'), ('charges_personnel', 'Charges personnel'), ('telephone_fixe', 'Téléphone fixe & internet'), ('telephone_cellulaire', 'Téléphone cellulaire'), ('entretien_vehicule', 'Entretien véhicule'), ('impots', 'Impôts'), ('bic', 'BIC'), ('patente', 'Patente'), ('cnps', 'CNPS'), ('entretien_informatique', 'Entretien informatique & télécom')], db_index=True, max_length=30, verbose_name='Ligne budgétaire')),
                ('nature_depense', models.CharField(choices=[('demande_achat', "Demande d'achat"), ('bon_commande', 'Bon de commande'), ('demande_paiement', 'Demande de paiement'), ('demande_travail', 'Demande de travail'), ('demande_absence', "Demande d'absence"), ('facture', 'Facture'), ('frais_mission', 'Frais de mission'), ('reservation', 'Réservation')], max_length=20, verbose_name='Nature de la dépense')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to=depenses.models.frais_generaux_upload_path, validators=[depenses.validators.validate_file_extension, depenses.validators.validate_file_size], verbose_name='Pièce jointe')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Dépense de frais généraux',
                'verbose_name_plural': 'Dépenses de frais généraux',
                'ordering': ['-date_saisie', '-date_creation'],
                'indexes': [models.Index(fields=['ligne_budgetaire', 'date_saisie'], name='depenses_de_ligne_b_54275b_idx')],
            },
        ),
    ]
