# Generated by Django 5.1.4 on 2026-04-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_historicaldepensefraisgeneraux_add_centre_budgetaire'),
        ('projets', '0002_add_fg_budget_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldepensefraisgeneraux',
            name='centre_budgetaire_id',
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='centre_budgetaire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projets.projet', verbose_name='Projet'),
        ),
    ]
