# Generated by Django 5.1.4 on 2026-04-14 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_remove_historicaldepensefraisgeneraux_centre_budgetaire_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depenseexploitation',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de décaissement'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='date_validation_dg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='date_validation_n1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation directeur'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='decaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décaissé par'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='motif_rejet_dg',
            field=models.TextField(blank=True, verbose_name='Motif rejet DG'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='motif_rejet_n1',
            field=models.TextField(blank=True, verbose_name='Motif rejet directeur'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve_n1', 'Approuvé (Directeur)'), ('approuve_dg', 'Approuvé (DG)'), ('rejete', 'Rejeté'), ('decaisse', 'Décaissé')], db_index=True, default='soumis', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (DG)'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='valide_par_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Directeur)'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de décaissement'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='date_validation_dg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='date_validation_n1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation directeur'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='decaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décaissé par'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='motif_rejet_dg',
            field=models.TextField(blank=True, verbose_name='Motif rejet DG'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='motif_rejet_n1',
            field=models.TextField(blank=True, verbose_name='Motif rejet directeur'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve_n1', 'Approuvé (Directeur)'), ('approuve_dg', 'Approuvé (DG)'), ('rejete', 'Rejeté'), ('decaisse', 'Décaissé')], db_index=True, default='soumis', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (DG)'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='valide_par_n1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Directeur)'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de décaissement'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='date_validation_dg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='date_validation_n1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation directeur'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='decaisse_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décaissé par'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='motif_rejet_dg',
            field=models.TextField(blank=True, verbose_name='Motif rejet DG'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='motif_rejet_n1',
            field=models.TextField(blank=True, verbose_name='Motif rejet directeur'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve_n1', 'Approuvé (Directeur)'), ('approuve_dg', 'Approuvé (DG)'), ('rejete', 'Rejeté'), ('decaisse', 'Décaissé')], db_index=True, default='soumis', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (DG)'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='valide_par_n1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Directeur)'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de décaissement'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='date_validation_dg',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation DG'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='date_validation_n1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validation directeur'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='decaisse_par',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décaissé par'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='motif_rejet_dg',
            field=models.TextField(blank=True, verbose_name='Motif rejet DG'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='motif_rejet_n1',
            field=models.TextField(blank=True, verbose_name='Motif rejet directeur'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve_n1', 'Approuvé (Directeur)'), ('approuve_dg', 'Approuvé (DG)'), ('rejete', 'Rejeté'), ('decaisse', 'Décaissé')], db_index=True, default='soumis', max_length=15, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='valide_par_dg',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (DG)'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='valide_par_n1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Directeur)'),
        ),
    ]
