# Generated by Django 5.1.4 on 2026-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0005_add_workflow_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenseexploitation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='depenseexploitation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='depensefraisgeneraux',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='historicaldepenseexploitation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='historicaldepensefraisgeneraux',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
    ]
