# Generated by Django 5.1.4 on 2026-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('chef', 'Directeur Général'), ('directeur_technique', 'Directeur Technique'), ('directeur_financier', 'Directeur Financier'), ('agent', 'Agent')], db_index=True, default='agent', max_length=25, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='role',
            field=models.CharField(choices=[('chef', 'Directeur Général'), ('directeur_technique', 'Directeur Technique'), ('directeur_financier', 'Directeur Financier'), ('agent', 'Agent')], db_index=True, default='agent', max_length=25, verbose_name='Rôle'),
        ),
    ]
