# Generated by Django 5.1.4 on 2026-03-17 17:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProjet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=255, verbose_name='Nom du projet')),
                ('designation', models.TextField(blank=True, verbose_name='Désignation / Description')),
                ('budget_etude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Étude (XOF)')),
                ('budget_materiel_equipement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Matériel & Équipement (XOF)')),
                ('budget_logistique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Logistique (XOF)')),
                ('budget_soustraitance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Sous-traitance (XOF)')),
                ('budget_frais_mission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Frais de Mission (XOF)')),
                ('depense_etude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Étude (XOF)')),
                ('depense_materiel_equipement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Matériel & Équipement (XOF)')),
                ('depense_logistique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Logistique (XOF)')),
                ('depense_soustraitance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Sous-traitance (XOF)')),
                ('depense_frais_mission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Frais de Mission (XOF)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Projet actif')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Projets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom du projet')),
                ('designation', models.TextField(blank=True, verbose_name='Désignation / Description')),
                ('budget_etude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Étude (XOF)')),
                ('budget_materiel_equipement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Matériel & Équipement (XOF)')),
                ('budget_logistique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Logistique (XOF)')),
                ('budget_soustraitance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Sous-traitance (XOF)')),
                ('budget_frais_mission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Frais de Mission (XOF)')),
                ('depense_etude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Étude (XOF)')),
                ('depense_materiel_equipement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Matériel & Équipement (XOF)')),
                ('depense_logistique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Logistique (XOF)')),
                ('depense_soustraitance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Sous-traitance (XOF)')),
                ('depense_frais_mission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé Frais de Mission (XOF)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Projet actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
