# Generated by Django 5.1.4 on 2026-04-14 21:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_assurance_sante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Assurance santé (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_bic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – BIC (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_charges_personnel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Charges personnel (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_cie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – CIE (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_cnps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – CNPS (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_dotation_carburant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Dotation carburant (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_entretien_informatique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Entretien informatique & télécom (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_entretien_vehicule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Entretien véhicule (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_fournitures_bureau',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Fournitures bureau (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_frais_taxi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Frais taxi (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_impots',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Impôts (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_loyers',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Loyers (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_patente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Patente (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_produits_entretien',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Produits entretien & droguerie (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_sodeci',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – SODECI (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_telephone_cellulaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Téléphone cellulaire (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='budget_fg_telephone_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Téléphone fixe & internet (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_assurance_sante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Assurance santé (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_bic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – BIC (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_charges_personnel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Charges personnel (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_cie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – CIE (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_cnps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – CNPS (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_dotation_carburant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Dotation carburant (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_entretien_informatique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Entretien informatique & télécom (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_entretien_vehicule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Entretien véhicule (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_fournitures_bureau',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Fournitures bureau (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_frais_taxi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Frais taxi (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_impots',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Impôts (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_loyers',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Loyers (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_patente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Patente (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_produits_entretien',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Produits entretien & droguerie (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_sodeci',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – SODECI (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_telephone_cellulaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Téléphone cellulaire (XOF)'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='depense_fg_telephone_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Téléphone fixe & internet (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_assurance_sante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Assurance santé (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_bic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – BIC (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_charges_personnel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Charges personnel (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_cie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – CIE (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_cnps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – CNPS (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_dotation_carburant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Dotation carburant (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_entretien_informatique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Entretien informatique & télécom (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_entretien_vehicule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Entretien véhicule (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_fournitures_bureau',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Fournitures bureau (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_frais_taxi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Frais taxi (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_impots',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Impôts (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_loyers',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Loyers (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_patente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Patente (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_produits_entretien',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Produits entretien & droguerie (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_sodeci',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – SODECI (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_telephone_cellulaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Téléphone cellulaire (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='budget_fg_telephone_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='FG – Téléphone fixe & internet (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_assurance_sante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Assurance santé (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_bic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – BIC (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_charges_personnel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Charges personnel (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_cie',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – CIE (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_cnps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – CNPS (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_dotation_carburant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Dotation carburant (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_entretien_informatique',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Entretien informatique & télécom (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_entretien_vehicule',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Entretien véhicule (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_fournitures_bureau',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Fournitures bureau (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_frais_taxi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Frais taxi (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_impots',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Impôts (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_loyers',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Loyers (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_patente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Patente (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_produits_entretien',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Produits entretien & droguerie (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_sodeci',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – SODECI (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_telephone_cellulaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Téléphone cellulaire (XOF)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='depense_fg_telephone_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Consommé FG – Téléphone fixe & internet (XOF)'),
        ),
    ]
