# Generated by Django 5.1.4 on 2026-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_add_fg_budget_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='projet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé (supprimé)'),
        ),
    ]
